server:
  port: 8080

spring:
  profiles:
    active: @spring.profile@

  datasource:
    url: jdbc:postgresql://localhost/psr
    username: postgres
    password: password

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  endpoint:
    logfile:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        include: '*'
logging:
  file:
    name: 'log/psr.log'