server:
  servlet:
    context-path: "/psr/api"

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost/psr
    username: postgres
    password: password
    initialization-mode: always
    schema: classpath:/sql/schema.sql
    data: classpath:/sql/data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: info
    com.rined.psr.portal: trace
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug